fix C compilation warning about function prototype in __SET_EXTERNAL
Example warning:
./POUS.c:1220:3: error: function declaration isn't a prototype [-Werror=strict-prototypes]
   __SET_EXTERNAL(data__->,KN_AUT,,__GET_VAR(data__->KEY_AUT.STATE_OUT));
   ^
compilation terminated due to -Wfatal-errors.
cc1: all warnings being treated as errors